# en: To update mise, ni, and pnpm, run `mise update`.
# jp: miseやni, pnpmをアップデートしたい時は `mise update` を実行する

[tools]
node = "lts"
pnpm = "latest"

[settings]
# Enable automatic updates
auto_install = true

[tasks.pnpm-update]
description = "Update pnpm to latest version"
run = "mise install pnpm@latest"
